services:
# Real Estate Data API Hosted
# using Django REST Framework
  django-service:
    restart: always
    container_name: django-service
    image: ghcr.io/kunalmehta14/realestate-django-service:1
    ports:
      - 8080:80
    volumes:
      - ./django-service/django-projects:/opt/app
    privileged: true
  ml-logic-service:
    restart: always
    container_name: ml-logic-service
    image: ghcr.io/kunalmehta14/realestate-ml-logic-service:1
    ports:
      - 8010:8010
    volumes:
      - ./ml-logic-service/src:/opt/src